DROP TABLE GameStats;
DROP TABLE Score;
DROP TABLE Player;
DROP TABLE Game;
DROP TABLE Team;
DROP TABLE Conference;
DROP TABLE Venue;

CREATE TABLE Venue (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	address VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	city VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	state CHAR(2) NOT NULL DEFAULT 'UNKNOWN',
	country VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	zipcode INTEGER NOT NULL DEFAULT 00000,
	capacity INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Conference (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	alias VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN'
);

CREATE TABLE Team (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	alias VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	venue_id VARCHAR(100) REFERENCES Venue(id),
	conference_id VARCHAR(100) NOT NULL REFERENCES Conference(id)
);

CREATE TABLE Game (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	home_team_id VARCHAR(100) NOT NULL REFERENCES Team(id),
	away_team_id VARCHAR(100) NOT NULL REFERENCES Team(id),
	--venue_id VARCHAR(100),
	scheduled VARCHAR(100) NOT NULL, —MAKE A DATETIME (has date and time associated with it)
	--network VARCHAR(100),
	--internet VARCHAR(100)
);

CREATE TABLE Player (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	last_name VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	team_id VARCHAR(100) NOT NULL REFERENCES Team(id),
	height INTEGER NOT NULL DEFAULT 0,
	weight INTEGER NOT NULL DEFAULT 0,
	jersey_number INTEGER NOT NULL DEFAULT 0,
	year VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	position VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
	birthplace VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN'
);

CREATE TABLE GameStats (
	game_id VARCHAR(100) NOT NULL REFERENCES Game(id),
	player_id VARCHAR(100) NOT NULL REFERENCES Player(id),
	minutes INTEGER NOT NULL DEFAULT 0,
	three_point_attempts INTEGER NOT NULL DEFAULT 0,
	three_point_makes INTEGER NOT NULL DEFAULT 0,
	two_point_attempts INTEGER NOT NULL DEFAULT 0,
	two_point_makes INTEGER NOT NULL DEFAULT 0,
	field_goal_attempts INTEGER NOT NULL DEFAULT 0,
	field_goal_makes INTEGER NOT NULL DEFAULT 0,
	free_throw_attempts INTEGER NOT NULL DEFAULT 0,
	free_throw_makes INTEGER NOT NULL DEFAULT 0,
	offensive_rebounds INTEGER NOT NULL DEFAULT 0,
	defensive_rebounds INTEGER NOT NULL DEFAULT 0,
	assists INTEGER NOT NULL DEFAULT 0,
	turnovers INTEGER NOT NULL DEFAULT 0,
	steals INTEGER NOT NULL DEFAULT 0,
	blocks INTEGER NOT NULL DEFAULT 0,
	personal_fouls INTEGER NOT NULL DEFAULT 0,
	technical_fouls INTEGER NOT NULL DEFAULT 0,
	flagrant_fouls INTEGER NOT NULL DEFAULT 0,
	points INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (game_id, player_id)
);

CREATE TABLE Score (
	game_id VARCHAR(100) NOT NULL REFERENCES Game(id),
	home_score INTEGER NOT NULL DEFAULT 0,
	away_score INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(game_id)
);
